const SERVER_ERROR_CODE = 500;
const SERVER_ERROR_MESSAGE = 'Ошибка сервера';
const INCORRECT_DATA_CODE = 400;
const INCORRECT_DATA_MESSAGE = 'Переданы некорректные данные';
const NOTFOUND_CODE = 404;
const NONEXISTENT_CARD_MESSAGE = 'Карточка с указанным id не найдена.';
module.exports = {
  SERVER_ERROR_CODE,
  INCORRECT_DATA_CODE,
  NOTFOUND_CODE,
  SERVER_ERROR_MESSAGE,
  INCORRECT_DATA_MESSAGE,
  NONEXISTENT_CARD_MESSAGE,
};